version: '3'

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: letmein
        ports:
            - "33060:3306"
        volumes:
            - "C:/DockerData/MySMS:/var/lib/mysql"
    
    www:
        build:
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - "database"
        ports:
            - "3000:3000"
        command: bundle exec rails s