version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: "always" 
    ports:
      - "3306:3306"
    volumes:
      - "C:/DockerData/MySMS:/var/lib/mysql"
    
  www:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "database"
    environment:
        DB_HOST: database
        DB_USER: root
        DB_PASSWORD: example
        DB_NAME: mysms_development
        DB_PORT: 3306
    ports:
    - "3000:3000"
    command: bundle exec rails s
